# Generated by Django 4.0.5 on 2022-06-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_alter_news_options_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категории', 'verbose_name_plural': 'категории'},
        ),
    ]
